### ISSUE TITLE
Markdown syntax: can we have a different flavour?

### ISSUE THREAD

**Issue by thisismygitrepo** [mfontanini/presenterm#137]
I've used `Marp` and `slidev` and both tools follow a syntax where `---` is the directive for `new slide`.
In `presenterm` however, its like `<-----!end slide ---->`

IMH:
* This is way more typing for someting as essential as new slide.
* This is way harder to remember
* This doesn't feel markdown-ish.

I really like `presenterm` and I'm wondering if it is possible to add option/ cli flag to choose syntax. I don't feel like its a low hanging fruit.
The advantage would be interopability and drop-in replacement for other popular tools.

Thanks.

**Comment by mfontanini** [comment]
Sure, now that there's a config file this can be added as an option. So you'll enable some option and that will let you use `---` to end a slide. I can add this tomorrow.

Do note that you can use [this option](https://github.com/mfontanini/presenterm/blob/master/docs/config.md#implicit_slide_ends) so slide ends are implicit so that may work for you if you're using slide titles in every slide.
