### ISSUE TITLE
Pause increments {current_slide} value

### ISSUE THREAD

**Issue by tranzystorek-io** [mfontanini/presenterm#16]
Using pauses increases the number of total slides and results in slide number incrementing per pause.

This isn't a huge issue, but might break the immersion slightly.

Verified on presenterm 0.2.1

**Comment by mfontanini** [comment]
Thanks for the report! For some reason I thought this is how it should be. Like if I were to do this in google slides, I'd create an incremental slide by copying the previous one so it _is_ a different slide. But I do agree that this is kind of weird, I'll look into it. We basically need the slides to be split into pieces and "jumping to the next" means "jump to the next chunk if possible otherwise slide".

**Comment by mfontanini** [comment]
Hey @tranzystorek-io this is fixed, feel free to verify this and let me know if anything looks off. Thanks!
