### ISSUE TITLE
[Request] Allow spawning processes inside presenterm

### ISSUE THREAD

**Issue by strottos** [mfontanini/presenterm#223]
Even just being able to spawn a default terminal would pretty much do.

I know technically I can always open another terminal, but sometimes I record my terminal to `asciinema` and it would be nice to be able to drive that with presenterm.

Not essential for many I'm sure, but a very nice to have for me.

**Comment by mfontanini** [comment]
Have you considered using tmux? You can spin up a separate window and do whatever you want over there. It also [integrates great with asciinema](https://gist.github.com/worldofprasanna/1861b182103cef452ec58471679a7e5b).

This would be a massive change and I think there's already tools to get around it. You can otherwise have a look at [lookatme](https://github.com/d0c-s4vage/lookatme) which has support for this.

**Comment by strottos** [comment]
Yeah that's fair. I have thought about things like tmux and that might be the answer. One problem I have with it is it's not Windows compatible.

I'll take a look at `lookatme` too. Haven't seen this previously, thanks.

Feel free to close this.
