### ISSUE TITLE
Support arbitrary html comments

### ISSUE THREAD

**Issue by pacak** [mfontanini/presenterm#23]
One of the main benefits of using pure text formats is ability to use a good text editor. One of the useful features of a good text editor is ability to fold and unfold boring parts of text. For example in vim anything between special tags  `{{{` and `}}}` can be folded into a single line. In most languages you'd use it along with comment specific to that language, in Rust it would be `// {{{` and `// }}}`.

Markdown uses HTML comments and vim automatically inserts them as `<!-- {{{ -->` and `<!-- }}} -->`. Sadly this makes `presenterm` very unhappy...

What I want is to be able to have text like this and `presenterm` behaving as if comments are not there
```
thread 'main' has overflowed its stack<!--{{{-->
fatal runtime error: stack overflow<!--}}}-->
```

**Comment by mfontanini** [comment]
Thanks for the report! This is now fixed in master. I'm curious how you got a stack overflow, I couldn't reproduce that. 

I did make the change so any comment that contains nothing but a `{{{` or `}}}` (after trimming!) is now ignored. Because comments can contain presenterm commands I need _some_ rule on how to determine they could be commands (and fail if they're bogus). So for now every HTML comment is a presenterm command unless it's a multi-line comment or one of `{{{` or `}}}`.

**Comment by pacak** [comment]
> I'm curious how you got a stack overflow, I couldn't reproduce that.

Stack overflow is just a sample text I used as an example unrelated to your crate :)

Thanks for a quick fix!

**Comment by mfontanini** [comment]
lol okay you said "Sadly this makes presenterm very unhappy" so a stack overflow seemed in line. Sweet!

**Comment by pacak** [comment]
Nah, I was referring to an error message. Btw, this makes it say that there's an error on line 1 column 2. In my file it's line 500+...

```
<!-- end_slide 1-->
```

**Comment by mfontanini** [comment]
lol nice one. I'll fix this one tomorrow!
