### ISSUE TITLE
Question: Can you set typst output width to 100%? instead of just centered?

### ISSUE THREAD

**Issue by chardskarth** [mfontanini/presenterm#232]

**Comment by mfontanini** [comment]
You can probably set the [typst PPI](https://mfontanini.github.io/presenterm/guides/latex.html#controlling-ppi) in the config file to be something pretty large. Images should still be capped so that they don't grow horizontally/vertically more than the terminal size so this way if you set it high enough it should cover the entire screen horizontally (as I presume that's the largest dimension of the two).

**Comment by chardskarth** [comment]
Thanks for the fast repl @mfontanini , is there a way instead to set typst rendered images aligned left?

**Comment by chardskarth** [comment]
Changing the width in typst works in the meantime. Changing ppi doesnt do anything. 

Closing for now. Thanks!
