### ISSUE TITLE
Code blocks are not wrappable

### ISSUE THREAD

**Issue by DrunkenToast** [mfontanini/presenterm#289]
Long text is currently not supported with code blocks, they won't wrap properly as the characters are styled but it wraps after the styling is done.
Preferably it would be wrapped before the styling is applied.

![image](https://github.com/user-attachments/assets/4d84ce6e-97e7-438d-ac69-82f7592dc18a)

---

Expected outcome (mind the line numbers).

![image](https://github.com/user-attachments/assets/83c70e4f-e0ca-4c25-9e28-9722586d58f8)

---

I would understand a "Won't fix" label, since styling like this can be a whole can of worms, and ultimately the writer can simply split up the lines himself.

This would however make it easier to present on different screen sizes (especially considering you can create columns) and make line numbers a bit more convenient.

**Comment by mfontanini** [comment]
This is something I'm aware of. Like you say, this could open up a can of worms. Also, in the way this is implemented, highlighting happens during presentation load time so it's not as easy as it sounds to do the wrapping because you only know where the end should be once the presentation is being displayed (as you need to know the window/rect size). I do see the issue though, so I'd like to have a look. It's just not as simple to fix as you'd imagine it should be unless things get moved around quite a bit.

**Comment by DrunkenToast** [comment]
> so it's not as easy as it sounds to do the wrapping

Oh no, don't get me wrong, it sounds terribly difficult!
Working text is hell-ish!

Just wanted to open this issue so it's being tracked :)
