### ISSUE TITLE
Links lose their titles

### ISSUE THREAD

**Issue by calebdw** [mfontanini/presenterm#325]
Hello!

Currently, markdown links (`[foo](https://foo.bar)`) lose their titles and the actual link is shown italicized and underlined:

![image](https://github.com/user-attachments/assets/d71916b0-530c-42e1-bdbb-ce93b6b6c2fe)

However, this removes context---oftentimes the link by itself doesn't tell me much. The title is there to explain the link or to hide away a lengthy url.

I have two ideas off the top of my head:

1. Show the *title* instead of the link, and open the link when the title is clicked on (would an actual link be possible in the terminal?)
2. If 1) is too complication / not doable, then show both, e.g., (the particular styling could be adjusted of course):
![image](https://github.com/user-attachments/assets/468f4410-4740-4967-91f1-1c3de396155d)

Thanks!

**Comment by DrunkenToast** [comment]
> Show the title instead of the link, and open the link when the title is clicked on (would an actual link be possible in the terminal?)
This is a thing, there are ansi codes for it. But afaik, support for it in terminals is very sparse. `printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'` apparently works but none of my terminals support clicking it.

**Comment by DrunkenToast** [comment]
> Show the title instead of the link, and open the link when the title is clicked on (would an actual link be possible in the terminal?)

This is a thing, there are ansi codes for it. But afaik, support for it in terminals is very sparse. `printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'` apparently works but none of my terminals support clicking it.

**Comment by mfontanini** [comment]
I'm curious where showing this makes sense. People won't be _running_ your presentations, at most they'll be opening the PDF output. I agree this is removing information that's present in markdown but also I don't see why you'd want to include this. It's mostly styling so you can always write 

```markdown
* Visit **my blog** [](https://my-blog.com).
```

And give it the style that you want. I chose to ignore the title in links because I honestly didn't see the point. Even in the PDF output you'd want to see the link. e.g. when you watch a presentation and they have references, you see plain links, not a link hidden behind some text.

**Comment by calebdw** [comment]
Hmm, what if you automatically gave the title some styling (like an underline/bold or both etc) if it's included?

E.g.,

```
* Visit [my blog](https://my-blog.com).
```

 - Visit  [my blog](https://my-blog.com) (https://my-blog.com)
