### ISSUE TITLE
How to  add code highligthing for a  new langage?

### ISSUE THREAD

**Issue by Trophime** [mfontanini/presenterm#362]
Hi, 
I wonder how to add support for a new langage.

I would like to give try to presenterm for creating slides for students.
The idea is to present the use of [gmsh](https://gmsh.info/).
 
I would like to have basic support for the geo file format of gmsh just like the [gmsh-vscode extension ](https://github.com/Bertbk/vscode-gmsh/tree/master).

Thanks for your feedback.
Best

**Comment by calebdw** [comment]
This uses [`bat`](https://github.com/sharkdp/bat) under the hood to actually do all the syntax highlighting. If the language is supported by `bat` then it should be as easy as https://github.com/mfontanini/presenterm/pull/361, otherwise this is in the same boat as https://github.com/mfontanini/presenterm/issues/271

**Comment by mfontanini** [comment]
Closing, feel free to reopen if needed. See #388 also for a way to invoke `bat` directly.
