### ISSUE TITLE
View output on acquire_terminal

### ISSUE THREAD

**Issue by orhun** [mfontanini/presenterm#373]
Sometimes I'm executing cargo commands for showing examples for TUI projects such as [tachyonfx](https://github.com/junkdog/tachyonfx):

````
```bash +exec +acquire_terminal
cargo run --manifest-path /home/orhun/gh/tachyonfx/Cargo.toml --example fx-chart
```
````

This works, but I am unable to see the cargo run output (i.e. build logs) so I sometimes wait on an empty terminal screen for 5-10 seconds which makes the presentation a bit strange to follow.

Would it be possible to also redirect stdout to the previous terminal when `acquire_terminal` is being used?

**Comment by mfontanini** [comment]
> wait on an empty terminal screen for 5-10 seconds

I created #375 which should help; rust-script caches dependencies so I imagine most time here is being spent linking and linking in release mode takes a lot longer (maybe use `mold` if you're not using it to speed this up?).

> Would it be possible to also redirect stdout to the previous terminal when `acquire_terminal` is being used?

The problem with this is if there's an error in your script, presenterm can't capture it so you'll get an "execution failed" message and nothing else. e.g. either I capture stderr (`cargo` writes to stderr, not stdout) and show you the error message on failure, or I don't capture it and you will see cargo's build logs but then if there's an error I can't show it to you. At best I can add an attribute like `+no_capture_stderr` that would indicate presenterm desn't capture stderr but if there's an error all you'll get is "execution failed". Would that work?

**Comment by orhun** [comment]
> (maybe use mold if you're not using it to speed this up?).

Good tip, will try!

> e.g. either I capture stderr (cargo writes to stderr, not stdout) and show you the error message on failure, or I don't capture it and you will see cargo's build logs but then if there's an error I can't show it to you

Wouldn't it be feasible to capture everything via using something like [`os_pipe`](https://docs.rs/os_pipe) and also redirect it to the terminal at the same time? Not sure if that'd actually work, just throwing an idea. 

> At best I can add an attribute like +no_capture_stderr that would indicate presenterm desn't capture stderr but if there's an error all you'll get is "execution failed". Would that work?

Yup that'd work - ofc if adding yet another option is not a big issue :)

**Comment by mfontanini** [comment]
I can't think of a nice way of solving this unfortunately. Something involving `os_pipe` would be pretty tricky, because it would need to capture and print stderr but only until the actual program is ran. e.g. you want the stderr that `rust-script` emits, but not the one that the compiled program emits.

Looking at your presentation, the hello world snippet takes a bit the first time but any subsequent run (even after closing and reopening presenterm) takes about a second. Of course not sure what hardware you're running this on but maybe this should be better now that this is using debug mode? Otherwise the thing you're doing to run `cargo run` on each snippet should be the way to go. Even if this printed something but took 10 seconds it would be a terrible UX so having things precompiled should be the way to go.

**Comment by orhun** [comment]
Yeah I see... I'm going to give this a try again, as you have said if I pre-compile the dependencies it shouldn't be a big problem.

**Comment by mfontanini** [comment]
Closing this as we can't do much unfortunately. Will re-open if a solution comes up.
