### ISSUE TITLE
Skip executed snippets on multiple pauses

### ISSUE THREAD

**Issue by orhun** [mfontanini/presenterm#374]
In some of my slides I have multiple executable snippets separated with pauses:

````
```bash +exec +acquire_terminal
command 1
```

<!-- pause -->

```bash +exec +acquire_terminal
command 2
```

<!-- pause -->

```bash +exec +acquire_terminal
command 3
```
````

As you might have guessed, I want to execute them in order as I progress in the presentation. However, when I get to the 2nd or 3rd command and press the execute key, it starts executing from the 1st one instead of where I left off.

I would expect it to skip the already executed ones when there are pauses in the slide. Is it reasonable or are there any other ways to achieve this? What do you think?

**Comment by mfontanini** [comment]
The way I did `acquire_terminal`, it will let you run the same script multiple times and this is what's causing the issue. Does re-running the same script N times make sense or should this only let you run it once? e.g. the issue is when you press control-e, presenterm tries to run everything visible that is runnable, so it goes one by one executing them. If these snippets were only executable once, it would automatically do what you want.

If in some case it makes sense to let you run it more than once and in others it doesn't we'd need a flag like `run_once` or something but this is becoming a big hack. Would letting `acquire_terminal` snippets run once just like the normal snippets make sense? That'd solve this. You can always control-r to refresh the entire presentation, which will let you run it again.

**Comment by orhun** [comment]
I agree that adding another flag would be hacky, instead we can make it run the snippets once which I think makes more sense :)

**Comment by mfontanini** [comment]
I created #376 to fix this. This also adds the separator bar like in any other executable snippet to `acquire_terminal` snippets so they look consistent + now you need a way to know that you've run them once you do. Can you give this a try?

**Comment by orhun** [comment]
Works like a charm, thanks!
