### ISSUE TITLE
Images are not shown when using tmux

### ISSUE THREAD

**Issue by yujinyuz** [mfontanini/presenterm#72]
I tried downloading the binary in the releases and also tried building it but still had the same problem.

The terminal just hangs whenever it's the image part and could not proceed further through the slides.

https://github.com/mfontanini/presenterm/assets/10972027/63e40205-9797-4fa7-8ac5-eee0f0dbedc3

I tried running without tmux and it was working just fine.

**Comment by yujinyuz** [comment]
@mfontanini Oh. Alright. I thought it was compatible with tmux since I can run `kitten icat examples/doge.png` just fine within tmux.

<img width="1109" alt="image" src="https://github.com/mfontanini/presenterm/assets/10972027/4eda916b-fda9-482d-a08e-3ba09fae47a3">

Does this app not use that command under the hood?

**Comment by mfontanini** [comment]
Hmm interesting... `kitty icat` may be skipping a step that the library this uses to print images uses, which may cause it to think tmux can't show images when it can. Under the hood this is running the same code that [viu](https://github.com/atanunq/viu) uses so this would need to be changed there.

**Comment by rmartine-ias** [comment]
Tmux actually supports sixel, now! https://www.arewesixelyet.com/#tmux

**Comment by mfontanini** [comment]
I don't think that's the case here. I could be wrong but I think both tmux and your terminal emulator would need to support sixel and kitty (which @yujinyuz is using doesn't). The  reason why this works on `kitty icat` is because that uses [some custom logic](https://github.com/kovidgoyal/kitty/blob/master/kittens/icat/transmit.go#L39-L43) to deal with tmux. Because we use `viuer`, this means that library would need to do the same.

**Comment by mfontanini** [comment]
Alright, this was fixed in #166 (only for the kitty terminal + tmux). See the notes there but tl;dr; you need to specify `--image-protocol kitty-local` for now _and_ gifs (I recently got these to work under kitty!) only work properly in the latest tmux 3.3a.

**Comment by yujinyuz** [comment]
Hi @mfontanini I just tried this again with tmux 3.4 and kitty using presenterm 0.7.0

Passing the `--image-protocol kitty-local` works but it doesn't render anything..

<img width="1728" alt="Screenshot 2024-03-11 at 00 51 01" src="https://github.com/mfontanini/presenterm/assets/10972027/45945124-9574-461e-99d0-e2581eaaf8f8">

It works properly without tmux though..
<img width="1728" alt="Screenshot 2024-03-11 at 00 51 21" src="https://github.com/mfontanini/presenterm/assets/10972027/06b54332-f70a-49b1-a0b3-3ddb60b6054c">

**Comment by mfontanini** [comment]
I forgot to clarify (and forgot myself this was necessary so I had to chase it down): you need to enable the `allow-passthrough` option in tmux (see [man](https://man.archlinux.org/man/tmux.1.en#allow-passthrough)). e.g. put this in your tmux.conf:

```
set-option -g allow-passthrough on
```

This allows tmux to pass through characters straight to the terminal emulator so it handles them rather than tmux doing so itself. In this case, this lets presenterm tell tmux that the escape codes to transmit images via the kitty protocol need to be forwarded to kitty, as it's the one drawing them.

**Comment by yujinyuz** [comment]
Awesome! That makes sense now.

It’s working properly now.

The only problem I see is that if you didn't pass the `image-protocol`, it just hangs and doesn't load.

But I can live with this and I just changed the default config.yaml.

**Comment by mfontanini** [comment]
Yeah I know, it's not great but I haven't spent the time to figure out how to do this properly without risking doing something wrong. At least the config file approach does it for now.

**Comment by AllenFind** [comment]
Even with all the settings above, iterm2 still cannot produce the image with tmux ;(

Tmux version: 3.4
presenterm: latest code build
command: presenterm test.md  --image-protocol iterm2

**Comment by mfontanini** [comment]
Are you using large image files? Does it also fail if you use a small image? e.g. a few KBs long

**Comment by AllenFind** [comment]
Hi,  I tested 1KB image. It still doesn't work.

**Comment by kkkfasya** [comment]
> Hi, I tested 1KB image. It still doesn't work.

same, i cant display my band logo still

**Comment by mfontanini** [comment]
#661 adds support for images in iterm2 + tmux. For now this only works for small images (byte wise); I'll make another change to use the newer multipart protocol that should make this work for larger images.
