### ISSUE TITLE
[Request] Specifiy colors in text

### ISSUE THREAD

**Issue by nshern** [mfontanini/presenterm#88]
I think it would be valuable to be able to specify colors for text, so that certain text elements could be emphasized.
I imagine it would be similar to how markdown is able to render it via html e.g.:
```
<span style="color:blue">some *blue* text</span>.
```

**Comment by mfontanini** [comment]
I think this is generally a good idea and I can see the usefulness of it. However, I'm afraid of doing something like this because:
a) The code will now need to start parsing HTML.
b) Once you start allowing _some_ HTML, more HTML parsing requests will inevitably be made. e.g. then we'll want entire divs with color. Then why not also allow alignment? Why not sub divs that split the text into columns?

I'd like to keep this open until enough people claim this should be a supported feature as I think it will open the door for a lot of complexity in the app.

**Comment by mfontanini** [comment]
That doesn't look bad actually... Maybe that's an alternative worth considering so we don't go down the html route.

**Comment by carbon-steel** [comment]
Definitely would love to see this. Especially if the colors could reference colors from the current theme.

**Comment by henryiii** [comment]
Is there a way to color just a word or section of words with the atters route?

**Comment by DrunkenToast** [comment]
> Is there a way to color just a word or section of words with the atters route?

There's a mention of bracketed spans so something like this: `this is [red text]{color:red}`, could work

**Comment by mfontanini** [comment]
This is fixed now, I ended up using `span`s to not add more custom syntax here. See #390 for more info. I may also add some palette or something to the theme so you can use `<span class="foo">` multiple times without having to spell out the colors every time but at least for now this unblocks this issue.
